import { AircraftConfig } from './types';

export const AIRCRAFT_CATALOG: AircraftConfig[] = [
    {
        id: 'cessna172',
        name: 'Cessna 172 Skyhawk',
        icon: '🛩️',
        category: 'TRAINER',
        description: 'Klassikaline 4-kohaline ühemootoriline propellerlennuk. Väga stabiilne ja ideaalne lennuoskuse lihvimiseks.',
        price: 0, // Unlocked by default!
        topSpeedKmh: 230,
        acceleration: 30,
        pitchRate: 1.4,
        rollRate: 1.8,
        yawRate: 0.9,
        mass: 1100,
        liftCoefficient: 1.0,
        explosionScale: 1.0,
        coinMultiplier: 1.0,
        colorPrimary: 0xf5f6fa,
        colorSecondary: 0x273c75,
        colorAccent: 0xe84118,
        meshType: 'cessna',
        debrisPieceCount: 6
    },
    {
        id: 'piper_cub',
        name: 'Piper Super Cub',
        icon: '🛩️',
        category: 'BUSH',
        description: 'Kerge kollane põllulennuk tohutute tundrarehvidega. Äärmiselt väle ja suudab maanduda suvalisele mäenõlvale.',
        price: 1000,
        topSpeedKmh: 205,
        acceleration: 36,
        pitchRate: 1.7,
        rollRate: 2.1,
        yawRate: 1.2,
        mass: 800,
        liftCoefficient: 1.25,
        explosionScale: 0.9,
        coinMultiplier: 1.1,
        colorPrimary: 0xf1c40f,
        colorSecondary: 0x2c3e50,
        colorAccent: 0x000000,
        meshType: 'piper',
        debrisPieceCount: 6
    },
    {
        id: 'pitts_special',
        name: 'Pitts Special S-2B',
        icon: '✈️',
        category: 'AEROBATIC',
        description: 'Kahetiivaline (biplane) akrobaatikalennuk. Pöörleb ümber oma telje välgukiirusel ja sobib ideaalselt 360° spinnide tegemiseks.',
        price: 2500,
        topSpeedKmh: 310,
        acceleration: 52,
        pitchRate: 2.4,
        rollRate: 3.6,
        yawRate: 1.8,
        mass: 750,
        liftCoefficient: 1.15,
        explosionScale: 1.1,
        coinMultiplier: 1.3,
        colorPrimary: 0xe74c3c,
        colorSecondary: 0xffffff,
        colorAccent: 0x2c3e50,
        meshType: 'biplane',
        debrisPieceCount: 8
    },
    {
        id: 'learjet45',
        name: 'Learjet 45',
        icon: '✈️',
        category: 'BUSINESS',
        description: 'Elegantne kahe turboreaktiivmootoriga äriklassi eralennuk. Suurepärane kiirendus ja muljetavaldav krahhiheli.',
        price: 5500,
        topSpeedKmh: 480,
        acceleration: 48,
        pitchRate: 1.5,
        rollRate: 2.0,
        yawRate: 1.0,
        mass: 9000,
        liftCoefficient: 0.95,
        explosionScale: 1.4,
        coinMultiplier: 1.5,
        colorPrimary: 0xffffff,
        colorSecondary: 0x1e272e,
        colorAccent: 0xd63031,
        meshType: 'bizjet',
        debrisPieceCount: 9
    },
    {
        id: 'spitfire',
        name: 'Supermarine Spitfire Mk IX',
        icon: '🛩️',
        category: 'WARBIRD',
        description: 'Legendaarne Teise maailmasõja hävituslennuk kuulsa Rolls-Royce Merlin mootoriga. Tuntud oma ellipsikujuliste tiibade poolest.',
        price: 9000,
        topSpeedKmh: 440,
        acceleration: 60,
        pitchRate: 2.0,
        rollRate: 2.7,
        yawRate: 1.4,
        mass: 3400,
        liftCoefficient: 1.1,
        explosionScale: 1.3,
        coinMultiplier: 1.7,
        colorPrimary: 0x4b6584,
        colorSecondary: 0x20bf6b,
        colorAccent: 0xf7b731,
        meshType: 'warbird',
        debrisPieceCount: 8
    },
    {
        id: 'boeing737',
        name: 'Boeing 737-800',
        icon: '🛫',
        category: 'AIRLINER',
        description: 'Maailma populaarseim reisilennuk. Raske mass ja tohutud reaktiivmootorid tekitavad allakukkumisel hiiglasliku krahhi!',
        price: 16000,
        topSpeedKmh: 520,
        acceleration: 35,
        pitchRate: 1.0,
        rollRate: 1.2,
        yawRate: 0.7,
        mass: 42000,
        liftCoefficient: 1.0,
        explosionScale: 2.2,
        coinMultiplier: 2.0,
        colorPrimary: 0xffffff,
        colorSecondary: 0x0984e3,
        colorAccent: 0xdfe6e9,
        meshType: 'airliner',
        debrisPieceCount: 12
    },
    {
        id: 'f16_falcon',
        name: 'F-16 Fighting Falcon',
        icon: '🚀',
        category: 'SUPERSONIC',
        description: 'Ülehelikiirusega mitmeotstarbeline hävitaja järelpõletiga. Äärmuslik manööverdusvõime ja plahvatuslik kiirus.',
        price: 28000,
        topSpeedKmh: 750,
        acceleration: 85,
        pitchRate: 2.6,
        rollRate: 4.0,
        yawRate: 1.9,
        mass: 12000,
        liftCoefficient: 0.9,
        explosionScale: 1.8,
        coinMultiplier: 2.4,
        colorPrimary: 0x57606f,
        colorSecondary: 0x2f3542,
        colorAccent: 0xff4757,
        meshType: 'fighter',
        debrisPieceCount: 10
    },
    {
        id: 'concorde',
        name: 'Concorde SST',
        icon: '✈️',
        category: 'SUPERSONIC',
        description: 'Legendaarne ülehelikiirusega reisilennuk unikaalse langetatava nina ja deltatiivaga. Hävitav löögijõud kokkupõrkel!',
        price: 45000,
        topSpeedKmh: 820,
        acceleration: 70,
        pitchRate: 1.2,
        rollRate: 1.6,
        yawRate: 0.8,
        mass: 78000,
        liftCoefficient: 0.85,
        explosionScale: 2.5,
        coinMultiplier: 2.8,
        colorPrimary: 0xf1f2f6,
        colorSecondary: 0x3742fa,
        colorAccent: 0xff4757,
        meshType: 'supersonic',
        debrisPieceCount: 12
    },
    {
        id: 'an225_mriya',
        name: 'Antonov An-225 Mriya',
        icon: '✈️',
        category: 'CARGO',
        description: 'Maailma raskeim 6-mootoriline transpordilennuk kahe sabatüüriga. Selle gigandi krahh raputab tervet kaarti!',
        price: 70000,
        topSpeedKmh: 490,
        acceleration: 30,
        pitchRate: 0.8,
        rollRate: 0.9,
        yawRate: 0.5,
        mass: 120000,
        liftCoefficient: 1.3,
        explosionScale: 3.5,
        coinMultiplier: 3.5,
        colorPrimary: 0xffffff,
        colorSecondary: 0x00a8ff,
        colorAccent: 0xfbc531,
        meshType: 'heavy_cargo',
        debrisPieceCount: 16
    },
    {
        id: 'b2_spirit',
        name: 'B-2 Spirit Stealth',
        icon: '🛸',
        category: 'STEALTH',
        description: 'Tippsalajane radareile nähtamatu lendtiib. Aerodünaamiline tulevikutäht hiiglasliku tiibade siruulatusega.',
        price: 110000,
        topSpeedKmh: 680,
        acceleration: 65,
        pitchRate: 1.4,
        rollRate: 2.0,
        yawRate: 1.1,
        mass: 55000,
        liftCoefficient: 1.1,
        explosionScale: 2.8,
        coinMultiplier: 4.2,
        colorPrimary: 0x1e272e,
        colorSecondary: 0x11141a,
        colorAccent: 0x57606f,
        meshType: 'stealth_wing',
        debrisPieceCount: 10
    },
    {
        id: 'space_shuttle',
        name: 'Space Shuttle Orbiter',
        icon: '🚀',
        category: 'HYPERSONIC',
        description: 'Kosmosesüstik taassisenemise kuumuskaitsekilpidega. Hüperhelikiiruselt langev kosmoselegend, mis tagab maksimaalse väljamakse!',
        price: 180000,
        topSpeedKmh: 950,
        acceleration: 95,
        pitchRate: 1.8,
        rollRate: 2.4,
        yawRate: 1.2,
        mass: 80000,
        liftCoefficient: 0.8,
        explosionScale: 4.0,
        coinMultiplier: 5.0,
        colorPrimary: 0xf8f9fa,
        colorSecondary: 0x121418,
        colorAccent: 0xe67e22,
        meshType: 'shuttle',
        debrisPieceCount: 14
    }
];

export function getAircraftById(id: string): AircraftConfig {
    return AIRCRAFT_CATALOG.find(a => a.id === id) || AIRCRAFT_CATALOG[0];
}
