import { TrainDef } from './types';

export const TRAINS_CATALOG: TrainDef[] = [
    // --- 🚂 RONGID / TRAINS ---
    {
        id: 'classic_steam',
        category: 'train',
        name: 'Klassikaline Auruvedur',
        nameEn: 'Classic Steam Locomotive',
        icon: '🚂',
        price: 0,
        maxSpeed: 90,
        acceleration: 1.0,
        passengers: 24,
        description: 'Autentne 19. sajandi auruvedur messingist viimistluse ja suitsukorstnaga.',
        descriptionEn: 'Authentic 19th-century steam locomotive with brass trims and working smokestack.',
        special: 'Autentne auruheli & suitsupahvakud',
        specialEn: 'Authentic steam audio & chimney puffs',
        style: 'classic_steam',
        locoColor: 0x1c2430,
        trimColor: 0xf59e0b,
        coachColor: 0xb91c1c
    },
    {
        id: 'heavy_diesel',
        category: 'train',
        name: 'Raske Diisel Kaubavedur',
        nameEn: 'Heavy Freight Diesel-Max',
        icon: '🚜',
        price: 150,
        maxSpeed: 105,
        acceleration: 1.2,
        passengers: 30,
        description: 'Võimas tööstuslik diiselvedur topeltpasunate ja suure veojõuga.',
        descriptionEn: 'Heavy-duty industrial diesel locomotive built for pulling long cargo freight.',
        special: 'Suur veojõud ja kaubaveo võimekus',
        specialEn: 'Massive tractive power & dual air horns',
        style: 'heavy_diesel',
        locoColor: 0xd97706,
        trimColor: 0x111827,
        coachColor: 0x78350f
    },
    {
        id: 'forest_shunter',
        category: 'train',
        name: 'Metsa Auru-Tankvedur',
        nameEn: 'Woodland Steam Shunter',
        icon: '🌲',
        price: 250,
        maxSpeed: 95,
        acceleration: 1.3,
        passengers: 28,
        description: 'Kompaktne metsaveo tankvedur, spetsialiseerunud kurvilistele radadele.',
        descriptionEn: 'Agile woodland tank locomotive specialized in winding forest tracks.',
        special: 'Suur stabiilsus mägikurvides',
        specialEn: 'Extreme stability around sharp bends',
        style: 'forest_shunter',
        locoColor: 0x166534,
        trimColor: 0xfacc15,
        coachColor: 0x14532d
    },
    {
        id: 'bullet_shinkansen',
        category: 'train',
        name: 'Super-Kiirrong Shinkansen',
        nameEn: 'High-Speed Bullet Shinkansen',
        icon: '⚡',
        price: 400,
        maxSpeed: 180,
        acceleration: 1.9,
        passengers: 55,
        description: 'Jaapani tipptehnoloogiline terava aerodünaamilise ninaga kuulirong.',
        descriptionEn: 'Japanese high-speed aerodynamic bullet train engineered for ultra-smooth velocity.',
        special: 'Aerodünaamiline nina & katuse pantograaf',
        specialEn: 'Aerodynamic nose & pantographs',
        style: 'bullet_shinkansen',
        locoColor: 0xf8fafc,
        trimColor: 0x0284c7,
        coachColor: 0x0369a1
    },
    {
        id: 'royal_orient',
        category: 'train',
        name: 'Kuldne Kuninglik Express',
        nameEn: 'Golden Royal Orient Express',
        icon: '🌌',
        price: 600,
        maxSpeed: 140,
        acceleration: 1.5,
        passengers: 48,
        description: 'Kuninglik luksusrong safiirsinise kere ja puhta kulla ornamentidega.',
        descriptionEn: 'Prestigious royal luxury train with sapphire blue coaches and gold ornaments.',
        special: 'Luksuslik interjöör & kuldsed laternad',
        specialEn: 'First-class luxury & gold lanterns',
        style: 'royal_orient',
        locoColor: 0x1e3a8a,
        trimColor: 0xfbbf24,
        coachColor: 0x172554
    },
    {
        id: 'alpine_climber',
        category: 'train',
        name: 'Alpi Mägironija',
        nameEn: 'Alpine Mountain Climber',
        icon: '🏔️',
        price: 800,
        maxSpeed: 130,
        acceleration: 1.7,
        passengers: 36,
        description: 'Šveitsi mägiraudtee rong panoraamklaasist vaatevagunitega.',
        descriptionEn: 'Swiss alpine railway train featuring full panoramic glass dome cars.',
        special: 'Panoraamvaade & mäeronimise võimekus',
        specialEn: 'Panoramic dome & steep hill climbing',
        style: 'alpine_climber',
        locoColor: 0x991b1b,
        trimColor: 0xe2e8f0,
        coachColor: 0x38bdf8
    },
    {
        id: 'cyber_bullet',
        category: 'train',
        name: 'Cyber-Kiirrong 2099',
        nameEn: 'Cyber Bullet 2099',
        icon: '⚡',
        price: 1000,
        maxSpeed: 220,
        acceleration: 2.3,
        passengers: 60,
        description: 'Tulevikulinna mattmust küberrong neoonsinise põhjavalgustusega.',
        descriptionEn: 'Futuristic matte-black bullet train with neon cybernetic glow.',
        special: 'Neoonvalgustus & küberkiirus',
        specialEn: 'Underglow neon & hyper velocity',
        style: 'cyber_bullet',
        locoColor: 0x09090b,
        trimColor: 0x00f2fe,
        coachColor: 0x18181b
    },
    {
        id: 'armored_dreadnought',
        category: 'train',
        name: 'Soomustatud Lahinguvedur',
        nameEn: 'Armored Dreadnought Train',
        icon: '🌋',
        price: 1500,
        maxSpeed: 115,
        acceleration: 1.2,
        passengers: 50,
        description: 'Raskete terasplaatide, kaitserauast sahkade ja topeltkorstnatega kindlus.',
        descriptionEn: 'Reinforced steel fortress train outfitted with battering plow and heavy plating.',
        special: 'Raske soomus & võimas prožektor',
        specialEn: 'Heavy armor plating & high-beam spotlights',
        style: 'armored_dreadnought',
        locoColor: 0x3f3f46,
        trimColor: 0xb91c1c,
        coachColor: 0x27272a
    },
    {
        id: 'hyperloop_plasma',
        category: 'train',
        name: 'Hyperloop Plasma Rong 3000',
        nameEn: 'Hyperloop Plasma Rail 3000',
        icon: '🚀',
        price: 2000,
        maxSpeed: 260,
        acceleration: 2.9,
        passengers: 80,
        description: 'Eksperimentaalne plasma-mootoriga monorail rong ulmelise kiirusega.',
        descriptionEn: 'Experimental plasma-thruster monorail engineered for next-gen speeds.',
        special: 'Lillakas plasmajoa efekt & tippkiirus 260 km/h',
        specialEn: 'Purple plasma thruster trail & 260 km/h top speed',
        style: 'hyperloop_plasma',
        locoColor: 0x581c87,
        trimColor: 0xd946ef,
        coachColor: 0x3b0764
    },

    // --- 🚇 METROOD / METROS ---
    {
        id: 'metro_standard',
        category: 'metro',
        name: 'Klassikaline Linna Metroo',
        nameEn: 'Classic City Subway Metro',
        icon: '🚇',
        price: 0,
        maxSpeed: 110,
        acceleration: 1.6,
        passengers: 50,
        description: 'Klassikaline linnatranspordi metroorong kollase kiirustriibu ja topeltustega.',
        descriptionEn: 'Classic city subway metro train with yellow speedline, double sliding doors and rapid departure.',
        special: 'Kiire kiirendus ja lai reisijateruum',
        specialEn: 'Rapid acceleration & wide passenger space',
        style: 'metro_standard',
        locoColor: 0x334155,
        trimColor: 0xfacc15,
        coachColor: 0x475569
    },
    {
        id: 'commuter_emu',
        category: 'metro',
        name: 'Linnalähirong Metro-Express',
        nameEn: 'City Commuter Metro Express',
        icon: '🚆',
        price: 100,
        maxSpeed: 125,
        acceleration: 1.5,
        passengers: 45,
        description: 'Voolujooneline reisirong kiireks linna- ja metrooliikluseks.',
        descriptionEn: 'Modern aerodynamic rapid-transit commuter train for regional and metro lines.',
        special: 'LED esituled & ergonoomiline salong',
        specialEn: 'LED headlights & ergonomic cabin',
        style: 'commuter_emu',
        locoColor: 0xdc2626,
        trimColor: 0xffffff,
        coachColor: 0xe2e8f0
    },
    {
        id: 'metro_tokyo',
        category: 'metro',
        name: 'Tokyo Yamanote Metroo',
        nameEn: 'Tokyo High-Capacity Metro',
        icon: '🎌',
        price: 300,
        maxSpeed: 130,
        acceleration: 1.8,
        passengers: 70,
        description: 'Rohelise signatuurtriibuga Jaapani metroo ülisuure reisijatemahu ja sujuva sõiduga.',
        descriptionEn: 'Japanese high-density metro with iconic lime green accents and ultra-smooth electric acceleration.',
        special: 'Ülisuur mahutavus (70 reisijat)',
        specialEn: 'Ultra high capacity (70 passengers)',
        style: 'metro_tokyo',
        locoColor: 0xe2e8f0,
        trimColor: 0x16a34a,
        coachColor: 0xcfdaf0
    },
    {
        id: 'metro_london',
        category: 'metro',
        name: 'London Tube Metroo',
        nameEn: 'London Underground Tube',
        icon: '🇬🇧',
        price: 500,
        maxSpeed: 115,
        acceleration: 1.7,
        passengers: 55,
        description: 'Ikooniline punase ninaga ja ümara profiiliga Londoni metroorong.',
        descriptionEn: 'Iconic red-cab circular tunnel subway train engineered for tight subterranean radii.',
        special: 'Ümar profiil & autentne helisignaal',
        specialEn: 'Round tube profile & distinct subway chime',
        style: 'metro_london',
        locoColor: 0xb91c1c,
        trimColor: 0x1d4ed8,
        coachColor: 0xf1f5f9
    },
    {
        id: 'metro_paris',
        category: 'metro',
        name: 'Pariisi Kummiratta Metroo',
        nameEn: 'Paris Rapid Rubber Metro',
        icon: '🇫🇷',
        price: 750,
        maxSpeed: 140,
        acceleration: 2.0,
        passengers: 65,
        description: 'Pariisi kõrgtehnoloogiline panoraamakendega automaatne metroorong.',
        descriptionEn: 'High-tech automated driverless Paris metro with panoramic glass front windshield.',
        special: 'Panoraamaken ja ülisujuv kummiratas-veermik',
        specialEn: 'Panoramic front glass & smooth rubber bogies',
        style: 'metro_paris',
        locoColor: 0x0284c7,
        trimColor: 0x38bdf8,
        coachColor: 0x0f172a
    },
    {
        id: 'metro_futuristic',
        category: 'metro',
        name: 'Neo-Küber Metroo 2100',
        nameEn: 'Neo Cyber-Metro 2100',
        icon: '🌌',
        price: 1200,
        maxSpeed: 190,
        acceleration: 2.5,
        passengers: 85,
        description: 'Magnetlevitatsioonil hõljuv neoonroheline tuleviku metroorong tehisintellekti juhtimisel.',
        descriptionEn: 'Next-generation AI-driven maglev subway train with cybernetic neon illumination.',
        special: 'Maglev hõljumine & 190 km/h tippkiirus',
        specialEn: 'Maglev hover & 190 km/h top velocity',
        style: 'metro_futuristic',
        locoColor: 0x09090b,
        trimColor: 0x10b981,
        coachColor: 0x1e293b
    }
];
