import * as THREE from 'three';
import { AircraftConfig, AirportConfig } from './types';

export const AIRCRAFT_CATALOG: AircraftConfig[] = [
    {
        id: 'cessna172',
        name: 'Cessna 172 Skyhawk',
        category: 'Trainer',
        description: 'Single-engine high-wing aircraft. Stable, forgiving, and ideal for learning flight mechanics.',
        icon: '🛩️',
        maxSpeedKnots: 140,
        cruiseSpeedKnots: 110,
        stallSpeedKnots: 45,
        climbRateFtMin: 750,
        rollRateDegSec: 50,
        pitchRateDegSec: 28,
        yawRateDegSec: 20,
        weightKg: 1100,
        wingSpanMeters: 11.0,
        engineType: 'propeller',
        engineCount: 1,
        primaryColor: 0x38bdf8,
        secondaryColor: 0xffffff,
        price: 0
    },
    {
        id: 'airliner_a320',
        name: 'Airbus A320neo',
        category: 'Commercial',
        description: 'Modern twin-turbofan narrow-body passenger jet with fly-by-wire stability and winglets.',
        icon: '✈️',
        maxSpeedKnots: 450,
        cruiseSpeedKnots: 360,
        stallSpeedKnots: 115,
        climbRateFtMin: 2500,
        rollRateDegSec: 32,
        pitchRateDegSec: 18,
        yawRateDegSec: 12,
        weightKg: 73500,
        wingSpanMeters: 35.8,
        engineType: 'jet',
        engineCount: 2,
        primaryColor: 0xf8fafc,
        secondaryColor: 0x0284c7,
        price: 500
    },
    {
        id: 'boeing_747',
        name: 'Boeing 747 Jumbo Jet',
        category: 'Commercial',
        description: 'The iconic "Queen of the Skies". Massive 4-engine widebody with an upper deck hump.',
        icon: '🛫',
        maxSpeedKnots: 520,
        cruiseSpeedKnots: 420,
        stallSpeedKnots: 135,
        climbRateFtMin: 3000,
        rollRateDegSec: 24,
        pitchRateDegSec: 14,
        yawRateDegSec: 10,
        weightKg: 180000,
        wingSpanMeters: 64.4,
        engineType: 'jet',
        engineCount: 4,
        primaryColor: 0xffffff,
        secondaryColor: 0x1e3a8a,
        price: 1200
    },
    {
        id: 'f22_raptor',
        name: 'F-22 Raptor',
        category: 'Fighter',
        description: '5th-generation stealth air superiority fighter. Supersonic cruise, thrust vectoring, and afterburners.',
        icon: '⚡',
        maxSpeedKnots: 950,
        cruiseSpeedKnots: 580,
        stallSpeedKnots: 90,
        climbRateFtMin: 8500,
        rollRateDegSec: 110,
        pitchRateDegSec: 55,
        yawRateDegSec: 40,
        weightKg: 19700,
        wingSpanMeters: 13.6,
        engineType: 'jet',
        engineCount: 2,
        hasAfterburner: true,
        primaryColor: 0x475569,
        secondaryColor: 0x1e293b,
        price: 2500
    },
    {
        id: 'concorde',
        name: 'Concorde SST',
        category: 'Supersonic',
        description: 'Supersonic passenger airliner with iconic delta wings and droop-snoot nose.',
        icon: '🚀',
        maxSpeedKnots: 800,
        cruiseSpeedKnots: 520,
        stallSpeedKnots: 140,
        climbRateFtMin: 4500,
        rollRateDegSec: 38,
        pitchRateDegSec: 20,
        yawRateDegSec: 15,
        weightKg: 78700,
        wingSpanMeters: 25.6,
        engineType: 'jet',
        engineCount: 4,
        primaryColor: 0xffffff,
        secondaryColor: 0xd97706,
        price: 3200
    },
    {
        id: 'seaplane',
        name: 'Twin Otter Seaplane',
        category: 'Seaplane',
        description: 'Rugged twin-turboprop with dual floating pontoons, capable of land and water touchdowns.',
        icon: '🌊',
        maxSpeedKnots: 160,
        cruiseSpeedKnots: 130,
        stallSpeedKnots: 50,
        climbRateFtMin: 1200,
        rollRateDegSec: 45,
        pitchRateDegSec: 25,
        yawRateDegSec: 22,
        weightKg: 3500,
        wingSpanMeters: 19.8,
        engineType: 'propeller',
        engineCount: 2,
        hasFloats: true,
        primaryColor: 0xf59e0b,
        secondaryColor: 0x1f2937,
        price: 800
    },
    {
        id: 'biplane',
        name: 'Pitts Special Biplane',
        category: 'Vintage',
        description: 'Dual-wing classic aerobatic biplane. Exceptionally agile roll rate and loop capability.',
        icon: '🎪',
        maxSpeedKnots: 175,
        cruiseSpeedKnots: 125,
        stallSpeedKnots: 48,
        climbRateFtMin: 2200,
        rollRateDegSec: 130,
        pitchRateDegSec: 60,
        yawRateDegSec: 45,
        weightKg: 700,
        wingSpanMeters: 5.3,
        engineType: 'propeller',
        engineCount: 1,
        primaryColor: 0xef4444,
        secondaryColor: 0xffffff,
        price: 600
    },
    {
        id: 'ufo',
        name: 'Apex UFO Saucer',
        category: 'Experimental',
        description: 'Alien antigravity saucer with vertical lift, omni-directional thrusters, and neon pulse glow.',
        icon: '🛸',
        maxSpeedKnots: 1200,
        cruiseSpeedKnots: 700,
        stallSpeedKnots: 0,
        climbRateFtMin: 12000,
        rollRateDegSec: 150,
        pitchRateDegSec: 90,
        yawRateDegSec: 90,
        weightKg: 5000,
        wingSpanMeters: 12.0,
        engineType: 'rocket',
        engineCount: 1,
        hasAfterburner: true,
        primaryColor: 0x10b981,
        secondaryColor: 0x047857,
        price: 5000
    }
];

export const AIRPORTS: AirportConfig[] = [
    {
        id: 'PLX',
        name: 'Playard International',
        code: 'PLX 09/27',
        runwayHeadingDeg: 90,
        runwayStart: new THREE.Vector3(-1200, 1.2, 0),
        runwayEnd: new THREE.Vector3(1200, 1.2, 0),
        runwayWidth: 50,
        runwayLength: 2400
    },
    {
        id: 'ISL',
        name: 'Island Atoll Outpost',
        code: 'ISL 18/36',
        runwayHeadingDeg: 0,
        runwayStart: new THREE.Vector3(3200, 1.2, -3500),
        runwayEnd: new THREE.Vector3(3200, 1.2, -2300),
        runwayWidth: 35,
        runwayLength: 1200
    },
    {
        id: 'ALP',
        name: 'Alpine Ridge Plateau',
        code: 'ALP 04/22',
        runwayHeadingDeg: 45,
        runwayStart: new THREE.Vector3(-3600, 240, -3200),
        runwayEnd: new THREE.Vector3(-2800, 240, -2400),
        runwayWidth: 30,
        runwayLength: 1100
    }
];

export const PILOT_RANKS = [
    { title: 'Cadet', minXP: 0, icon: '🎖️' },
    { title: 'First Officer', minXP: 200, icon: '⭐' },
    { title: 'Captain', minXP: 600, icon: '⭐⭐' },
    { title: 'Chief Commander', minXP: 1500, icon: '👑' },
    { title: 'Ace Aviator', minXP: 3000, icon: '🏆' }
];
